name: Workflow security analysis

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: Spillgebees/admin/.github/workflows/zizmor.yml@7c82d25eedae42584afa948d230191ed2cd5e2b3 # main
